//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class BellCostFromWL_2015_09
    {
        public int id { get; set; }
        public Nullable<int> Registration { get; set; }
        public string AccountNumber { get; set; }
        public string SubscriberPhoneNo { get; set; }
        public Nullable<double> CostOfServicePlan { get; set; }
        public Nullable<double> SuspensionRate { get; set; }
        public Nullable<double> CostOfBilledAirtimeMinutes { get; set; }
        public Nullable<double> CostOfUsVoiceRoamingMinutesNonPlan { get; set; }
        public Nullable<double> CostOfCanadatoCanadaLdMinutesNonPlan { get; set; }
        public Nullable<double> CostOfCanadaToUsLdMinutesNonPlan { get; set; }
        public Nullable<double> CostOfCanadaToInternationalLdMinutes { get; set; }
        public Nullable<double> CostOfUstoCanadaLdMinutesNonPlan { get; set; }
        public Nullable<double> CostOfUsToUsLdMinutesNonPlan { get; set; }
        public Nullable<double> CostOfUsToInternationalLdMinuteNonPlan { get; set; }
        public Nullable<double> CostOfInternationalCallingMinutesNonPlan { get; set; }
        public Nullable<double> CostOfOutgoingSmsMessagesinUsNonPlan { get; set; }
        public Nullable<double> CostOfInternationalSmsMessagesNonPlan { get; set; }
        public Nullable<double> CostOfMmsPictures { get; set; }
        public Nullable<double> CostOfMmsVideos { get; set; }
        public Nullable<double> CostOfMBsDataOnMobilePhones { get; set; }
        public Nullable<double> CostOfMBsAbove500MBsOn500MBsDataPlans { get; set; }
        public Nullable<double> CostOfMBsAbove5GBon5GBsDataPlans { get; set; }
        public Nullable<double> CostOfMBsOfUsDataRoamingNonPlan { get; set; }
        public Nullable<double> CostOfMbsOfInternationalDataRoamingNonPlan { get; set; }
        public Nullable<double> CostOfCanadaToCanadaUsLdMinutesUnderMonthlyCdnLdPlan { get; set; }
        public Nullable<double> CostOf30DayUsVoiceRoamingPlan { get; set; }
        public Nullable<double> CostOfUsRoamingMinutesUnderUsVoiceRoamingPlan { get; set; }
        public Nullable<double> CostOfOneTimeUnlockingFee { get; set; }
        public Nullable<double> CostOf30dayUsDataRoamingPlan { get; set; }
        public Nullable<double> CostOfUsRoamingMBsUnderUsDataRoamingPlan { get; set; }
        public Nullable<double> CostOf30dayUsSmsRoamingPlan { get; set; }
        public Nullable<double> CostOfUsSmsMessagesUnderUsSmsRoamingPlan { get; set; }
        public Nullable<double> CostOf30dayInternationalVoiceRoamingPlan { get; set; }
        public Nullable<double> CostOfInternationalRoamingMinutesUnderInternationalVoiceRoamingPlan { get; set; }
        public Nullable<double> CostOf30dayInternationalDataRoamingPlan { get; set; }
        public Nullable<double> CostOfInternationalRoamingMBsUnderInternationalDataRoamingPlan { get; set; }
        public Nullable<double> CostOf30dayInternationalSmsRoamingPlan { get; set; }
        public Nullable<double> CostOfInternationalSmsMessagesUnderInternationalSmsRoamingPlan { get; set; }
        public Nullable<double> CostOfOptionalService911AccessFee { get; set; }
        public Nullable<double> CostOfOptionalServiceBbEmailInt1GBNorthAmerica { get; set; }
        public Nullable<double> CostOfOptionalServiceDetailBilling { get; set; }
        public Nullable<double> CostOfOptionalServiceGovCanBBerryTethering500MB { get; set; }
        public Nullable<double> CostOfOptionalServiceGovCanBBerryTethering5GB { get; set; }
        public Nullable<double> CostOfOptionalServiceMobileTV { get; set; }
        public Nullable<double> CostOfOptionalServiceNBGovt911Fee { get; set; }
        public Nullable<double> CostOfOptionalServiceNSGovt911Fee { get; set; }
        public Nullable<double> CostOfOptionalServicePEIGovt911Fee { get; set; }
        public Nullable<double> CostOfOptionalServiceSasktelCallDispInOut { get; set; }
        public Nullable<double> CostOfOptionalServiceStaticIP { get; set; }
        public Nullable<double> CostOfOptionalServiceUnlimitedTextMessaging { get; set; }
        public Nullable<double> CostOfOptionalServiceVisualVoiceMail { get; set; }
        public Nullable<double> CostOfOptionalServiceVoiceMailPlus { get; set; }
        public Nullable<double> CostOfOptionalServiceVoiceMailToText { get; set; }
        public Nullable<double> TotalOtherChargesAndCredits { get; set; }
        public Nullable<double> GstTaxForServices { get; set; }
        public Nullable<double> HstTaxForServices { get; set; }
        public Nullable<double> QstTaxForServices { get; set; }
        public Nullable<double> TotalCostForServices { get; set; }
        public Nullable<double> CostofOptionalServiceANOMALOUS1 { get; set; }
        public Nullable<double> CostofOptionalServiceDataBlockAntiSpam { get; set; }
        public Nullable<double> CostofOptionalServiceDataBlock { get; set; }
        public Nullable<double> CostofOptionalServiceGovCanSmartTethering500MB { get; set; }
        public Nullable<double> CostofOptionalServiceGovCanSmartTethering5GB { get; set; }
        public Nullable<double> CostofOptionalServiceGPSNAVPhones { get; set; }
        public Nullable<double> CostofOptionalServiceGPSNav1 { get; set; }
        public Nullable<double> CostofOptionalServiceNoAnswerTransfer { get; set; }
        public Nullable<double> CostofOptionalServicePublicDynamicIP { get; set; }
        public Nullable<double> CostofOptionalServicePushtotalkUnlimitedCdn { get; set; }
        public Nullable<double> CostofOptionalServiceQuebecmunicipal911tax { get; set; }
        public Nullable<double> CostofOptionalServiceSiriusSatelliteRadio { get; set; }
        public Nullable<double> CostofOptionalServiceStaticIPAtlantic { get; set; }
        public Nullable<double> CostofOptionalServiceStaticIPONQC { get; set; }
        public Nullable<double> CostofOptionalServiceStaticIPWestPrairiesNWT { get; set; }
        public Nullable<double> CostofOptionalServiceUnlimited104 { get; set; }
        public Nullable<double> CostofOptionalService1MBUSData { get; set; }
        public Nullable<double> CostofOptionalServiceSAF75Yr911Svc010911 { get; set; }
        public Nullable<double> CostofOptionalServiceEmailInternetBlackBerry1GB { get; set; }
        public Nullable<double> CostofOptionalServiceDynamicIP { get; set; }
        public Nullable<double> CostofOptionalServiceSAF625911Fee21911Fee { get; set; }
        public Nullable<double> CostofOptionalServiceSysAccessFee895911Fee { get; set; }
        public Nullable<double> CostOfMonthlyCdnLdPlan { get; set; }
        public Nullable<double> CostofOptionalServiceDetailedAccountActivity { get; set; }
    }
}
