//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingDetail
    {
        public int Department { get; set; }
        public int Sequence { get; set; }
        public long StructureNumber { get; set; }
        public long PropertyNumber { get; set; }
        public Nullable<System.DateTime> LeaseExpiryDate { get; set; }
        public Nullable<bool> Custodian { get; set; }
        public Nullable<int> Tenant { get; set; }
        public Nullable<int> FTE { get; set; }
        public Nullable<bool> DataCentre { get; set; }
        public Nullable<bool> VideoConferencing { get; set; }
        public Nullable<bool> ContactCentre { get; set; }
        public Nullable<int> PBX { get; set; }
        public Nullable<bool> KeySystem { get; set; }
        public Nullable<bool> Satellite { get; set; }
        public Nullable<bool> EmailTransformation { get; set; }
        public string Notes { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual TenantType TenantType { get; set; }
        public virtual TenantType TenantType1 { get; set; }
    }
}
