//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkDataEntry
    {
        public string PhoneNumber { get; set; }
        public string LineStatus { get; set; }
        public string LineCategory { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Building { get; set; }
        public string SoReason { get; set; }
        public string SoDueDate { get; set; }
        public string SoNumber { get; set; }
        public Nullable<System.DateTime> TBOO_DATE { get; set; }
        public string CTC_AccessoryStatus { get; set; }
        public string CTC_Exemption { get; set; }
        public string CTC_Comment { get; set; }
        public string LineUsage { get; set; }
    }
}
