//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int city_id { get; set; }
        public string prov_cd { get; set; }
        public string city_nm_eng { get; set; }
        public string city_nm_fre { get; set; }
    
        public virtual Province Province { get; set; }
    }
}
