//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRA
    {
        public int ID { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> Region { get; set; }
        public string LanID { get; set; }
        public Nullable<int> Exemption { get; set; }
        public Nullable<int> Accessory { get; set; }
        public Nullable<bool> Holster { get; set; }
        public string Fax { get; set; }
        public Nullable<int> ExemptionType { get; set; }
        public Nullable<int> AccessoryStatus { get; set; }
        public Nullable<int> CentrexOutOrderNumber { get; set; }
        public Nullable<System.DateTime> OutOrderDate { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual ExemptionType ExemptionType1 { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Region Region1 { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
