//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentAgency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepartmentAgency()
        {
            this.NAT_ALIANT = new HashSet<NAT_ALIANT>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameFromAB { get; set; }
        public string NameFromAliant { get; set; }
        public Nullable<int> Partner { get; set; }
        public string Comment { get; set; }
        public string ShortName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ALIANT> NAT_ALIANT { get; set; }
        public virtual Department Department { get; set; }
    }
}
