//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.BellUsageFromWLs = new HashSet<BellUsageFromWL>();
            this.BellUsageFromWL_2014_01 = new HashSet<BellUsageFromWL_2014_01>();
            this.BellUsageFromWL_2014_04 = new HashSet<BellUsageFromWL_2014_04>();
            this.Branches = new HashSet<Branch>();
            this.BuildingDetails = new HashSet<BuildingDetail>();
            this.DepartmentAgencies = new HashSet<DepartmentAgency>();
            this.NAT_ALIANT = new HashSet<NAT_ALIANT>();
            this.Devices = new HashSet<Device>();
            this.Devices1 = new HashSet<Device>();
            this.Devices_History = new HashSet<Devices_History>();
            this.Devices_History1 = new HashSet<Devices_History>();
            this.NAT_NWTel = new HashSet<NAT_NWTel>();
            this.OBMs = new HashSet<OBM>();
            this.Registrations = new HashSet<Registration>();
            this.Registrations1 = new HashSet<Registration>();
            this.Registrations2 = new HashSet<Registration>();
            this.RegistrationsV2 = new HashSet<RegistrationsV2>();
            this.RogersUsageFromWL_2014_04 = new HashSet<RogersUsageFromWL_2014_04>();
            this.RogersUsageFromWL_2014_01 = new HashSet<RogersUsageFromWL_2014_01>();
            this.UnusedWLs = new HashSet<UnusedWL>();
            this.UnusedWL_WP = new HashSet<UnusedWL_WP>();
            this.Wirelesses = new HashSet<Wireless>();
            this.WL_2014_04 = new HashSet<WL_2014_04>();
        }
    
        public int ID { get; set; }
        public string Department_eng { get; set; }
        public string Department_fra { get; set; }
        public Nullable<int> Population { get; set; }
        public string NameFromRogers { get; set; }
        public string NameFromBell { get; set; }
        public string NameFromOBM_eng { get; set; }
        public string NameFromOBM_fra { get; set; }
        public Nullable<int> Portfolio { get; set; }
        public string AlphaID { get; set; }
        public string NameFromAliant { get; set; }
        public string NameFromAB { get; set; }
        public string NameFromBC { get; set; }
        public Nullable<bool> isPartnerSSC { get; set; }
        public string Comments { get; set; }
        public string ShortName { get; set; }
        public string NagFromOBM { get; set; }
        public string Hostname { get; set; }
        public string NameFromTelusPCS { get; set; }
        public string NameFromTelusMike { get; set; }
        public string NameFromGEDS { get; set; }
        public string NameFromBES { get; set; }
        public string EmailFromBES { get; set; }
        public Nullable<int> DepartmentFromAVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BellUsageFromWL> BellUsageFromWLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BellUsageFromWL_2014_01> BellUsageFromWL_2014_01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BellUsageFromWL_2014_04> BellUsageFromWL_2014_04 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildingDetail> BuildingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentAgency> DepartmentAgencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ALIANT> NAT_ALIANT { get; set; }
        public virtual Portfolio Portfolio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devices_History> Devices_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devices_History> Devices_History1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_NWTel> NAT_NWTel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBM> OBMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationsV2> RegistrationsV2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RogersUsageFromWL_2014_04> RogersUsageFromWL_2014_04 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RogersUsageFromWL_2014_01> RogersUsageFromWL_2014_01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnusedWL> UnusedWLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnusedWL_WP> UnusedWL_WP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wireless> Wirelesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WL_2014_04> WL_2014_04 { get; set; }
    }
}
