//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices_2015_11_01
    {
        public string PhoneNumber { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public Nullable<int> Provider { get; set; }
        public Nullable<int> MonthAdd { get; set; }
        public Nullable<int> MonthOut { get; set; }
        public string Account { get; set; }
        public Nullable<int> Department { get; set; }
        public string SubscriberName { get; set; }
        public Nullable<bool> IsUnused { get; set; }
        public Nullable<int> EAP_STATUS { get; set; }
        public string CTC_OutOrderNumber { get; set; }
        public Nullable<int> CTC_Exemption { get; set; }
        public Nullable<int> CTC_AccessoryStatus { get; set; }
        public string CTC_Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string SR { get; set; }
        public string WO { get; set; }
        public string EAP_Comments { get; set; }
        public string WorkLocation { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<System.DateTime> TBOO_DATE { get; set; }
        public string KeepJustification { get; set; }
        public Nullable<int> KeepChoice { get; set; }
        public Nullable<int> USOC { get; set; }
        public string Email { get; set; }
        public string ApproverEmail { get; set; }
        public Nullable<int> LineUsage { get; set; }
        public Nullable<System.DateTime> ExemptionDate { get; set; }
        public string FilePath { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string EmployeeComments { get; set; }
    }
}
