//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighUsageExemption
    {
        public string CellularNumber { get; set; }
        public int Exemption { get; set; }
        public string Justification { get; set; }
        public string NameFromBilling { get; set; }
        public Nullable<int> DeviceTypeFromBilling { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual DeviceTypesFromBilling DeviceTypesFromBilling { get; set; }
        public virtual HighUsageExemptionType HighUsageExemptionType { get; set; }
    }
}
