//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAT_ALIANT
    {
        public string Number { get; set; }
        public Nullable<int> Registration { get; set; }
        public string Account { get; set; }
        public string Date { get; set; }
        public Nullable<int> Department { get; set; }
        public string Department_eng { get; set; }
        public string DeptIdFromAliant { get; set; }
        public Nullable<int> DepartmentAgency { get; set; }
    
        public virtual DepartmentAgency DepartmentAgency1 { get; set; }
        public virtual Department Department1 { get; set; }
    }
}
