//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAT_DMS_2014
    {
        public string ServiceNo { get; set; }
        public Nullable<int> Registration { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> DepartmentAgency { get; set; }
        public string CustName { get; set; }
        public string DepartmentName { get; set; }
        public string CustAcronym { get; set; }
        public string CustomerGroup { get; set; }
        public string CLID { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string RmAptNo { get; set; }
        public string Province { get; set; }
        public string CountyCd { get; set; }
        public string PostalCode { get; set; }
        public string Switch { get; set; }
        public string Len { get; set; }
        public string SetType { get; set; }
        public string NCOS { get; set; }
        public string HqClientCode { get; set; }
    }
}
