//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAT_MTS
    {
        public string Number { get; set; }
        public Nullable<int> Registration { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> DepartmentAgency { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string BillingAggregatorID { get; set; }
        public string BillingAggregatorCIN { get; set; }
        public string BillingAggregatorName { get; set; }
        public string BillingAccountID { get; set; }
        public string BillingAccountName { get; set; }
        public string UnitID { get; set; }
        public string UnitServiceType { get; set; }
        public string LocationID { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string AnalogDigital { get; set; }
    }
}
