//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBM_HISTORY
    {
        public string NumberBilled { get; set; }
        public string Information { get; set; }
        public string Level3Node { get; set; }
        public string Level4Node { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> RegistrationsID { get; set; }
        public Nullable<int> DepartmentFromOBM { get; set; }
        public string Month { get; set; }
    }
}
