//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtectedType
    {
        public int ID { get; set; }
        public Nullable<bool> Name { get; set; }
        public Nullable<bool> SocialNumber { get; set; }
        public Nullable<bool> TaxPayerSalary { get; set; }
        public Nullable<bool> PRI { get; set; }
        public Nullable<bool> EmployeeSalary { get; set; }
        public Nullable<bool> LetterOfOffer { get; set; }
        public Nullable<bool> LearningPlan { get; set; }
        public Nullable<bool> PerformanceEval { get; set; }
        public Nullable<bool> Audit { get; set; }
        public Nullable<bool> Design { get; set; }
        public Nullable<bool> SecurityEval { get; set; }
        public Nullable<bool> OtherProtectedType { get; set; }
        public string OtherProtectedTypeDesc { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
