//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickDeviceData
    {
        public string PhoneNumber { get; set; }
        public string LineCategory { get; set; }
        public string ServiceProviders { get; set; }
        public Nullable<int> MonthAdd { get; set; }
        public Nullable<int> MonthOut { get; set; }
        public string Account { get; set; }
        public string SubscriberName { get; set; }
        public string Departments { get; set; }
        public Nullable<bool> IsUnused { get; set; }
        public string LineStatus { get; set; }
        public string SoNumber { get; set; }
        public string CTC_Exemption { get; set; }
        public string CTC_AccessoryStatus { get; set; }
        public string CTC_Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string SoDueDate { get; set; }
        public string EAP_Comments { get; set; }
        public string StreetAddress { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<System.DateTime> TBOO_DATE { get; set; }
        public string KeepJustification { get; set; }
        public string KeepChoice { get; set; }
        public string USOC { get; set; }
        public string Email { get; set; }
        public string ApproverEmail { get; set; }
        public string LineUsage { get; set; }
        public Nullable<System.DateTime> ExemptionDate { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string EmployeeComments { get; set; }
        public int Version { get; set; }
        public string DepartmentsFromBilling { get; set; }
        public string SoReason { get; set; }
        public string Building { get; set; }
    }
}
