//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> Department { get; set; }
        public string WorkLocation { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public string LandLine { get; set; }
        public string CellularNumber1 { get; set; }
        public Nullable<bool> DataServices1 { get; set; }
        public Nullable<int> DeviceType1 { get; set; }
        public Nullable<int> ServiceProvider1 { get; set; }
        public string Other1 { get; set; }
        public string CellularNumber2 { get; set; }
        public Nullable<bool> DataServices2 { get; set; }
        public Nullable<int> DeviceType2 { get; set; }
        public Nullable<int> ServiceProvider2 { get; set; }
        public string Other2 { get; set; }
        public string CellularNumber3 { get; set; }
        public Nullable<bool> DataServices3 { get; set; }
        public Nullable<int> DeviceType3 { get; set; }
        public Nullable<int> ServiceProvider3 { get; set; }
        public string Other3 { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorPhone { get; set; }
        public string Extension { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public string AccountFromOBM { get; set; }
        public string NumberBilledFromOBM { get; set; }
        public Nullable<int> DepartmentFromOBM { get; set; }
        public Nullable<int> LandLineType { get; set; }
        public Nullable<int> LandLineProvider { get; set; }
        public string AccountFromWireless { get; set; }
        public string NumberBilledFromWireless { get; set; }
        public string SubscriberNameFromWireless { get; set; }
        public Nullable<int> DepartmentFromWireless { get; set; }
        public Nullable<int> ServiceProviderFromWireless { get; set; }
        public Nullable<bool> IsExempted { get; set; }
        public Nullable<bool> IsLandlineDisconnected { get; set; }
        public string ShortAddress { get; set; }
        public Nullable<int> LevStructureNumber { get; set; }
        public Nullable<double> LevPrecision { get; set; }
        public Nullable<int> JaroStructureNumber { get; set; }
        public Nullable<double> JaroPrecision { get; set; }
        public string FloorNumber { get; set; }
        public string OfficeNumber { get; set; }
        public Nullable<bool> IsDuplicate { get; set; }
        public Nullable<int> EapStatus { get; set; }
        public Nullable<int> DialerResult { get; set; }
        public Nullable<int> ObmMonthAdd { get; set; }
        public Nullable<int> ObmMonthOut { get; set; }
        public Nullable<bool> IsInGeds { get; set; }
        public Nullable<int> UsocType { get; set; }
        public Nullable<bool> Keep { get; set; }
        public string Justification { get; set; }
        public Nullable<int> DeviceTypeFromBilling1 { get; set; }
        public Nullable<int> DeviceTypeFromBilling2 { get; set; }
        public Nullable<int> DeviceTypeFromBilling3 { get; set; }
        public Nullable<bool> IsLetterExcluded { get; set; }
        public Nullable<int> ToBeOutOrderedDate { get; set; }
        public Nullable<bool> ToBeOutOrdered { get; set; }
        public Nullable<bool> IsBoardroom { get; set; }
        public Nullable<int> CTC_Exemption { get; set; }
        public Nullable<int> CTC_AccessoryStatus { get; set; }
        public string CTC_CentrexOutOrderNumber { get; set; }
        public Nullable<System.DateTime> CTC_OutOrderDate { get; set; }
        public string CTC_Comments { get; set; }
        public string CTC_EmailStatus { get; set; }
        public string CTC_ReasonForNotDisconnecting { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual CRA CRA { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual Department Department3 { get; set; }
        public virtual DeviceTypesFromBilling DeviceTypesFromBilling { get; set; }
        public virtual DeviceTypesFromBilling DeviceTypesFromBilling1 { get; set; }
        public virtual DeviceTypesFromBilling DeviceTypesFromBilling2 { get; set; }
        public virtual DeviceTypesFromSurvey DeviceTypesFromSurvey { get; set; }
        public virtual DeviceTypesFromSurvey DeviceTypesFromSurvey1 { get; set; }
        public virtual DeviceTypesFromSurvey DeviceTypesFromSurvey2 { get; set; }
        public virtual DialerStatu DialerStatu { get; set; }
        public virtual ExemptionType ExemptionType { get; set; }
        public virtual LandLineProvider LandLineProvider1 { get; set; }
        public virtual LandLineType LandLineType1 { get; set; }
        public virtual OLD_Quarters OLD_Quarters { get; set; }
        public virtual ProtectedType ProtectedType { get; set; }
        public virtual UsocType UsocType1 { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual ServiceProvider ServiceProvider4 { get; set; }
        public virtual ServiceProvider ServiceProvider5 { get; set; }
        public virtual ServiceProvider ServiceProvider6 { get; set; }
    }
}
