//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelusEBOD_2014_08
    {
        public int Id { get; set; }
        public string phonenumber { get; set; }
        public System.DateTime billing_date { get; set; }
        public int ClientID { get; set; }
    }
}
