//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnusedWL
    {
        public string SubscriberPhoneNo { get; set; }
        public string SubscriberName { get; set; }
        public Nullable<int> Department { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public Nullable<int> Registration { get; set; }
        public Nullable<int> WirelessType { get; set; }
        public Nullable<int> ServiceProvider { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public string StatusOfDevice { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual DeviceTypesFromBilling DeviceTypesFromBilling { get; set; }
        public virtual ServiceProvider ServiceProvider1 { get; set; }
    }
}
