//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class USOC
    {
        public string USOC1 { get; set; }
        public string ShortDesc { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual UsocType UsocType { get; set; }
    }
}
