//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class ActionLog
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string Username { get; set; }
    	[DataMember]
        public string ActionLogged { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Date { get; set; }
    }
}
