//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class aspnet_Users
    {
    	[DataMember]
        public System.Guid ApplicationId { get; set; }
    	[DataMember]
        public System.Guid UserId { get; set; }
    	[DataMember]
        public string UserName { get; set; }
    	[DataMember]
        public string LoweredUserName { get; set; }
    	[DataMember]
        public string MobileAlias { get; set; }
    	[DataMember]
        public bool IsAnonymous { get; set; }
    	[DataMember]
        public System.DateTime LastActivityDate { get; set; }
    }
}
