//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class BellFromEcare_2015_12
    {
    	[DataMember]
        public string Account { get; set; }
    	[DataMember]
        public string InvoiceDate { get; set; }
    	[DataMember]
        public string Number { get; set; }
    	[DataMember]
        public string Lastname { get; set; }
    	[DataMember]
        public string Firstname { get; set; }
    	[DataMember]
        public string Reference { get; set; }
    	[DataMember]
        public Nullable<double> AdjAppTotal { get; set; }
    	[DataMember]
        public Nullable<double> MonthlyChargeTotal { get; set; }
    	[DataMember]
        public Nullable<double> FtrChargeTotal { get; set; }
    	[DataMember]
        public string AirDuration { get; set; }
    	[DataMember]
        public Nullable<double> AirtimeCharge { get; set; }
    	[DataMember]
        public Nullable<double> DataCharge { get; set; }
    	[DataMember]
        public Nullable<double> RoamerCharge { get; set; }
    	[DataMember]
        public Nullable<double> RoamerLD { get; set; }
    	[DataMember]
        public Nullable<double> LDCharge { get; set; }
    	[DataMember]
        public Nullable<double> OtherCharges { get; set; }
    	[DataMember]
        public Nullable<double> DiscTotal { get; set; }
    	[DataMember]
        public Nullable<double> TotalCharges { get; set; }
    	[DataMember]
        public Nullable<int> TxtMsg { get; set; }
    	[DataMember]
        public string TxtMsgAmt { get; set; }
    	[DataMember]
        public string DataDuration { get; set; }
    	[DataMember]
        public string LdDuration { get; set; }
    	[DataMember]
        public string RoamingDuration { get; set; }
    	[DataMember]
        public string RoamingDataDuration { get; set; }
    	[DataMember]
        public Nullable<double> RoamingDataCharge { get; set; }
    	[DataMember]
        public Nullable<double> PktDataVol { get; set; }
    	[DataMember]
        public Nullable<double> PktDataAmt { get; set; }
    	[DataMember]
        public Nullable<double> GST { get; set; }
    	[DataMember]
        public Nullable<double> HST { get; set; }
    	[DataMember]
        public Nullable<double> HST_PEI { get; set; }
    	[DataMember]
        public Nullable<double> HST_ON { get; set; }
    	[DataMember]
        public Nullable<double> HST_BC { get; set; }
    	[DataMember]
        public Nullable<double> ORST { get; set; }
    	[DataMember]
        public Nullable<double> QST_TELEC { get; set; }
    	[DataMember]
        public Nullable<double> QST_OTHER { get; set; }
    	[DataMember]
        public Nullable<double> PST_PEI { get; set; }
    	[DataMember]
        public Nullable<double> PST_BC { get; set; }
    	[DataMember]
        public Nullable<double> PST_SK { get; set; }
    	[DataMember]
        public Nullable<double> PST_MB { get; set; }
    	[DataMember]
        public Nullable<double> ForeignTax { get; set; }
    	[DataMember]
        public string Duration10_4P { get; set; }
    	[DataMember]
        public Nullable<double> Amt10_4P { get; set; }
    	[DataMember]
        public string Duration10_4G { get; set; }
    	[DataMember]
        public Nullable<double> Amt10_4G { get; set; }
    	[DataMember]
        public string Roaming10_4 { get; set; }
    	[DataMember]
        public Nullable<double> RoamingAmt10_4 { get; set; }
    	[DataMember]
        public string MinutesDay { get; set; }
    	[DataMember]
        public string MinutesWeekEnd { get; set; }
    	[DataMember]
        public string MinutesNight { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public int id { get; set; }
    }
}
