//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Country))]
    [KnownType(typeof(InterestType))]
    [KnownType(typeof(PrimaryUse))]
    [KnownType(typeof(RegistrationsV2))]
    
    public partial class Building
    {
        public Building()
        {
            this.RegistrationsV2 = new HashSet<RegistrationsV2>();
        }
    
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public Nullable<int> Sequence { get; set; }
    	[DataMember]
        public long StructureNumber { get; set; }
    	[DataMember]
        public long PropertyNumber { get; set; }
    	[DataMember]
        public Nullable<int> PrimaryUse { get; set; }
    	[DataMember]
        public string UseSubCategory { get; set; }
    	[DataMember]
        public string PropertyName { get; set; }
    	[DataMember]
        public Nullable<int> InterestType { get; set; }
    	[DataMember]
        public string AddressLine1 { get; set; }
    	[DataMember]
        public string AddressLine2 { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string Province { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public Nullable<int> Country { get; set; }
    	[DataMember]
        public Nullable<double> Latitude { get; set; }
    	[DataMember]
        public Nullable<double> Longitude { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> EarliestLeaseExpiry { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> EarliestLeaseOI { get; set; }
    	[DataMember]
        public Nullable<bool> MultiTenant { get; set; }
    	[DataMember]
        public Nullable<int> NumberOfTenants { get; set; }
    	[DataMember]
        public Nullable<int> FTE { get; set; }
    	[DataMember]
        public Nullable<int> Population { get; set; }
    	[DataMember]
        public Nullable<int> GcnetSiteCode { get; set; }
    	[DataMember]
        public Nullable<int> WanNumberPartners { get; set; }
    	[DataMember]
        public Nullable<int> NumberOfWanLinks { get; set; }
    	[DataMember]
        public Nullable<double> TotalBandwidth { get; set; }
    	[DataMember]
        public Nullable<double> BandwidthAvgPerFTE { get; set; }
    	[DataMember]
        public Nullable<bool> WanLink { get; set; }
    	[DataMember]
        public string PlannedFYLan { get; set; }
    	[DataMember]
        public Nullable<int> GensWan { get; set; }
    	[DataMember]
        public Nullable<int> GensLan { get; set; }
    	[DataMember]
        public string GensIpTel { get; set; }
    	[DataMember]
        public Nullable<bool> DataCentre { get; set; }
    	[DataMember]
        public string PotentialClosing { get; set; }
    	[DataMember]
        public string PartnersSupported { get; set; }
    	[DataMember]
        public Nullable<bool> Videoconferencing { get; set; }
    	[DataMember]
        public Nullable<int> VcNumberOfInstances { get; set; }
    	[DataMember]
        public string Partners { get; set; }
    	[DataMember]
        public Nullable<bool> PBX { get; set; }
    	[DataMember]
        public Nullable<int> NumberOfPBX { get; set; }
    	[DataMember]
        public Nullable<bool> KeySystems { get; set; }
    	[DataMember]
        public Nullable<int> NumberOfKeySystems { get; set; }
    	[DataMember]
        public Nullable<bool> Centrex { get; set; }
    	[DataMember]
        public Nullable<int> NumberOfCentrexLines { get; set; }
    	[DataMember]
        public Nullable<bool> Satellite { get; set; }
    	[DataMember]
        public Nullable<int> NumberOfSatellites { get; set; }
    	[DataMember]
        public Nullable<bool> ContactCentre { get; set; }
    	[DataMember]
        public Nullable<int> ETI { get; set; }
    	[DataMember]
        public string EAP3 { get; set; }
    	[DataMember]
        public string EAP4 { get; set; }
    	[DataMember]
        public Nullable<int> CNS4 { get; set; }
    	[DataMember]
        public string EAP5 { get; set; }
    	[DataMember]
        public string EapVC { get; set; }
    	[DataMember]
        public string EAP81 { get; set; }
    	[DataMember]
        public string EAP82 { get; set; }
    	[DataMember]
        public string SCNetDeviceID { get; set; }
    	[DataMember]
        public Nullable<bool> Canarie { get; set; }
    	[DataMember]
        public Nullable<bool> Workplace2 { get; set; }
    	[DataMember]
        public Nullable<bool> SidArchived { get; set; }
    	[DataMember]
        public Nullable<bool> PidArchived { get; set; }
    	[DataMember]
        public string Notes { get; set; }
    	[DataMember]
        public string Questionable { get; set; }
    	[DataMember]
        public string Vacant3rdParty { get; set; }
    	[DataMember]
        public Nullable<int> NumberOfNonSscPartners { get; set; }
    	[DataMember]
        public string F64 { get; set; }
    	[DataMember]
        public string FacilityManagers { get; set; }
    	[DataMember]
        public string ShortAddress { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> CreatedDate { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    	[DataMember]
        public string ModifiedBy { get; set; }
    
    	[DataMember]
        public virtual Country Country1 { get; set; }
    	[DataMember]
        public virtual InterestType InterestType1 { get; set; }
    	[DataMember]
        public virtual PrimaryUse PrimaryUse1 { get; set; }
    	[DataMember]
        public virtual ICollection<RegistrationsV2> RegistrationsV2 { get; set; }
    }
}
