//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class BuildingsWithNoSID
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public Nullable<int> Sequence { get; set; }
    	[DataMember]
        public Nullable<long> StructureNumber { get; set; }
    	[DataMember]
        public Nullable<long> PropertyNumber { get; set; }
    	[DataMember]
        public string PrimaryUse { get; set; }
    	[DataMember]
        public string UseSubCategory { get; set; }
    	[DataMember]
        public string PropertyName { get; set; }
    	[DataMember]
        public string InterestType { get; set; }
    	[DataMember]
        public string AddressLine1 { get; set; }
    	[DataMember]
        public string AddressLine2 { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string Province { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public string Country { get; set; }
    	[DataMember]
        public Nullable<double> Latitude { get; set; }
    	[DataMember]
        public Nullable<double> Longitude { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> EarliestLeaseExpiry { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> EarliestLeaseOI { get; set; }
    	[DataMember]
        public string MultiTenant { get; set; }
    	[DataMember]
        public Nullable<double> NumberOfTenants { get; set; }
    	[DataMember]
        public Nullable<double> FTE { get; set; }
    	[DataMember]
        public Nullable<double> Population { get; set; }
    	[DataMember]
        public Nullable<double> GcnetSiteCode { get; set; }
    	[DataMember]
        public Nullable<double> WanNumberPartners { get; set; }
    	[DataMember]
        public Nullable<double> NumberOfWanLinks { get; set; }
    	[DataMember]
        public Nullable<double> TotalBandwidth { get; set; }
    	[DataMember]
        public Nullable<double> BandwidthAvgPerFTE { get; set; }
    	[DataMember]
        public string WanLink { get; set; }
    	[DataMember]
        public string PlannedFYLan { get; set; }
    	[DataMember]
        public Nullable<double> GensWan { get; set; }
    	[DataMember]
        public Nullable<double> GensLan { get; set; }
    	[DataMember]
        public string GensIpTel { get; set; }
    	[DataMember]
        public string DataCentre { get; set; }
    	[DataMember]
        public string PotentialClosing { get; set; }
    	[DataMember]
        public string PartnersSupported { get; set; }
    	[DataMember]
        public string Videoconferencing { get; set; }
    	[DataMember]
        public Nullable<double> VcNumberOfInstances { get; set; }
    	[DataMember]
        public string Partners { get; set; }
    	[DataMember]
        public string PBX { get; set; }
    	[DataMember]
        public string NumberOfPBX { get; set; }
    	[DataMember]
        public string KeySystems { get; set; }
    	[DataMember]
        public string NumberOfKeySystems { get; set; }
    	[DataMember]
        public string Centrex { get; set; }
    	[DataMember]
        public Nullable<double> NumberOfCentrexLines { get; set; }
    	[DataMember]
        public string Satellite { get; set; }
    	[DataMember]
        public string NumberOfSatellites { get; set; }
    	[DataMember]
        public string ContactCentre { get; set; }
    	[DataMember]
        public string ETI { get; set; }
    	[DataMember]
        public string EAP3 { get; set; }
    	[DataMember]
        public string EAP4 { get; set; }
    	[DataMember]
        public Nullable<double> CNS4 { get; set; }
    	[DataMember]
        public string EAP5 { get; set; }
    	[DataMember]
        public string EapVC { get; set; }
    	[DataMember]
        public string EAP81 { get; set; }
    	[DataMember]
        public string EAP82 { get; set; }
    	[DataMember]
        public string SCNetDevice_ID { get; set; }
    	[DataMember]
        public string Canarie { get; set; }
    	[DataMember]
        public string Workplace2 { get; set; }
    	[DataMember]
        public string SidArchived { get; set; }
    	[DataMember]
        public string PidArchived { get; set; }
    	[DataMember]
        public string Notes { get; set; }
    	[DataMember]
        public string Questionable { get; set; }
    	[DataMember]
        public string Vacant3rdParty { get; set; }
    	[DataMember]
        public Nullable<double> NumberOfNonSscPartners { get; set; }
    	[DataMember]
        public string F64 { get; set; }
    	[DataMember]
        public string FacilityManagers { get; set; }
    	[DataMember]
        public string ShortAddress { get; set; }
    }
}
