//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Province))]
    
    public partial class City
    {
    	[DataMember]
        public int city_id { get; set; }
    	[DataMember]
        public string prov_cd { get; set; }
    	[DataMember]
        public string city_nm_eng { get; set; }
    	[DataMember]
        public string city_nm_fre { get; set; }
    
    	[DataMember]
        public virtual Province Province { get; set; }
    }
}
