//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Building))]
    [KnownType(typeof(Registration))]
    [KnownType(typeof(RegistrationsV2))]
    
    public partial class Country
    {
        public Country()
        {
            this.Buildings = new HashSet<Building>();
            this.Registrations = new HashSet<Registration>();
            this.RegistrationsV2 = new HashSet<RegistrationsV2>();
        }
    
    	[DataMember]
        public int COUNTRY_ID { get; set; }
    	[DataMember]
        public string COUNTRY_CD { get; set; }
    	[DataMember]
        public string COUNTRY_ENG_NM { get; set; }
    	[DataMember]
        public string COUNTRY_FRE_NM { get; set; }
    
    	[DataMember]
        public virtual ICollection<Building> Buildings { get; set; }
    	[DataMember]
        public virtual ICollection<Registration> Registrations { get; set; }
    	[DataMember]
        public virtual ICollection<RegistrationsV2> RegistrationsV2 { get; set; }
    }
}
