//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Branch))]
    [KnownType(typeof(ExemptionType))]
    [KnownType(typeof(Location))]
    [KnownType(typeof(Region))]
    [KnownType(typeof(Registration))]
    
    public partial class CRA
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public Nullable<int> Location { get; set; }
    	[DataMember]
        public Nullable<int> Branch { get; set; }
    	[DataMember]
        public Nullable<int> Region { get; set; }
    	[DataMember]
        public string LanID { get; set; }
    	[DataMember]
        public Nullable<int> Exemption { get; set; }
    	[DataMember]
        public Nullable<int> Accessory { get; set; }
    	[DataMember]
        public Nullable<bool> Holster { get; set; }
    	[DataMember]
        public string Fax { get; set; }
    	[DataMember]
        public Nullable<int> ExemptionType { get; set; }
    	[DataMember]
        public Nullable<int> AccessoryStatus { get; set; }
    	[DataMember]
        public Nullable<int> CentrexOutOrderNumber { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> OutOrderDate { get; set; }
    
    	[DataMember]
        public virtual Branch Branch1 { get; set; }
    	[DataMember]
        public virtual ExemptionType ExemptionType1 { get; set; }
    	[DataMember]
        public virtual Location Location1 { get; set; }
    	[DataMember]
        public virtual Region Region1 { get; set; }
    	[DataMember]
        public virtual Registration Registration { get; set; }
    }
}
