//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(NAT_ALIANT))]
    [KnownType(typeof(Department))]
    
    public partial class DepartmentAgency
    {
        public DepartmentAgency()
        {
            this.NAT_ALIANT = new HashSet<NAT_ALIANT>();
        }
    
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string NameFromAB { get; set; }
    	[DataMember]
        public string NameFromAliant { get; set; }
    	[DataMember]
        public Nullable<int> Partner { get; set; }
    	[DataMember]
        public string Comment { get; set; }
    	[DataMember]
        public string ShortName { get; set; }
    
    	[DataMember]
        public virtual ICollection<NAT_ALIANT> NAT_ALIANT { get; set; }
    	[DataMember]
        public virtual Department Department { get; set; }
    }
}
