//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BellUsageFromWL))]
    [KnownType(typeof(BellUsageFromWL_2014_01))]
    [KnownType(typeof(BellUsageFromWL_2014_04))]
    [KnownType(typeof(Branch))]
    [KnownType(typeof(BuildingDetail))]
    [KnownType(typeof(DepartmentAgency))]
    [KnownType(typeof(NAT_ALIANT))]
    [KnownType(typeof(Portfolio))]
    [KnownType(typeof(Device))]
    [KnownType(typeof(Devices_History))]
    [KnownType(typeof(NAT_NWTel))]
    [KnownType(typeof(OBM))]
    [KnownType(typeof(Registration))]
    [KnownType(typeof(RegistrationsV2))]
    [KnownType(typeof(RogersUsageFromWL_2014_04))]
    [KnownType(typeof(RogersUsageFromWL_2014_01))]
    [KnownType(typeof(UnusedWL))]
    [KnownType(typeof(UnusedWL_WP))]
    [KnownType(typeof(Wireless))]
    [KnownType(typeof(WL_2014_04))]
    
    public partial class Department
    {
        public Department()
        {
            this.BellUsageFromWLs = new HashSet<BellUsageFromWL>();
            this.BellUsageFromWL_2014_01 = new HashSet<BellUsageFromWL_2014_01>();
            this.BellUsageFromWL_2014_04 = new HashSet<BellUsageFromWL_2014_04>();
            this.Branches = new HashSet<Branch>();
            this.BuildingDetails = new HashSet<BuildingDetail>();
            this.DepartmentAgencies = new HashSet<DepartmentAgency>();
            this.NAT_ALIANT = new HashSet<NAT_ALIANT>();
            this.Devices = new HashSet<Device>();
            this.Devices1 = new HashSet<Device>();
            this.Devices_History = new HashSet<Devices_History>();
            this.Devices_History1 = new HashSet<Devices_History>();
            this.NAT_NWTel = new HashSet<NAT_NWTel>();
            this.OBMs = new HashSet<OBM>();
            this.Registrations = new HashSet<Registration>();
            this.Registrations1 = new HashSet<Registration>();
            this.Registrations2 = new HashSet<Registration>();
            this.RegistrationsV2 = new HashSet<RegistrationsV2>();
            this.RogersUsageFromWL_2014_04 = new HashSet<RogersUsageFromWL_2014_04>();
            this.RogersUsageFromWL_2014_01 = new HashSet<RogersUsageFromWL_2014_01>();
            this.UnusedWLs = new HashSet<UnusedWL>();
            this.UnusedWL_WP = new HashSet<UnusedWL_WP>();
            this.Wirelesses = new HashSet<Wireless>();
            this.WL_2014_04 = new HashSet<WL_2014_04>();
        }
    
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string Department_eng { get; set; }
    	[DataMember]
        public string Department_fra { get; set; }
    	[DataMember]
        public Nullable<int> Population { get; set; }
    	[DataMember]
        public string NameFromRogers { get; set; }
    	[DataMember]
        public string NameFromBell { get; set; }
    	[DataMember]
        public string NameFromOBM_eng { get; set; }
    	[DataMember]
        public string NameFromOBM_fra { get; set; }
    	[DataMember]
        public Nullable<int> Portfolio { get; set; }
    	[DataMember]
        public string AlphaID { get; set; }
    	[DataMember]
        public string NameFromAliant { get; set; }
    	[DataMember]
        public string NameFromAB { get; set; }
    	[DataMember]
        public string NameFromBC { get; set; }
    	[DataMember]
        public Nullable<bool> isPartnerSSC { get; set; }
    	[DataMember]
        public string Comments { get; set; }
    	[DataMember]
        public string ShortName { get; set; }
    	[DataMember]
        public string NagFromOBM { get; set; }
    	[DataMember]
        public string Hostname { get; set; }
    	[DataMember]
        public string NameFromTelusPCS { get; set; }
    	[DataMember]
        public string NameFromTelusMike { get; set; }
    	[DataMember]
        public string NameFromGEDS { get; set; }
    	[DataMember]
        public string NameFromBES { get; set; }
    	[DataMember]
        public string EmailFromBES { get; set; }
    	[DataMember]
        public Nullable<int> DepartmentFromAVT { get; set; }
    
    	[DataMember]
        public virtual ICollection<BellUsageFromWL> BellUsageFromWLs { get; set; }
    	[DataMember]
        public virtual ICollection<BellUsageFromWL_2014_01> BellUsageFromWL_2014_01 { get; set; }
    	[DataMember]
        public virtual ICollection<BellUsageFromWL_2014_04> BellUsageFromWL_2014_04 { get; set; }
    	[DataMember]
        public virtual ICollection<Branch> Branches { get; set; }
    	[DataMember]
        public virtual ICollection<BuildingDetail> BuildingDetails { get; set; }
    	[DataMember]
        public virtual ICollection<DepartmentAgency> DepartmentAgencies { get; set; }
    	[DataMember]
        public virtual ICollection<NAT_ALIANT> NAT_ALIANT { get; set; }
    	[DataMember]
        public virtual Portfolio Portfolio1 { get; set; }
    	[DataMember]
        public virtual ICollection<Device> Devices { get; set; }
    	[DataMember]
        public virtual ICollection<Device> Devices1 { get; set; }
    	[DataMember]
        public virtual ICollection<Devices_History> Devices_History { get; set; }
    	[DataMember]
        public virtual ICollection<Devices_History> Devices_History1 { get; set; }
    	[DataMember]
        public virtual ICollection<NAT_NWTel> NAT_NWTel { get; set; }
    	[DataMember]
        public virtual ICollection<OBM> OBMs { get; set; }
    	[DataMember]
        public virtual ICollection<Registration> Registrations { get; set; }
    	[DataMember]
        public virtual ICollection<Registration> Registrations1 { get; set; }
    	[DataMember]
        public virtual ICollection<Registration> Registrations2 { get; set; }
    	[DataMember]
        public virtual ICollection<RegistrationsV2> RegistrationsV2 { get; set; }
    	[DataMember]
        public virtual ICollection<RogersUsageFromWL_2014_04> RogersUsageFromWL_2014_04 { get; set; }
    	[DataMember]
        public virtual ICollection<RogersUsageFromWL_2014_01> RogersUsageFromWL_2014_01 { get; set; }
    	[DataMember]
        public virtual ICollection<UnusedWL> UnusedWLs { get; set; }
    	[DataMember]
        public virtual ICollection<UnusedWL_WP> UnusedWL_WP { get; set; }
    	[DataMember]
        public virtual ICollection<Wireless> Wirelesses { get; set; }
    	[DataMember]
        public virtual ICollection<WL_2014_04> WL_2014_04 { get; set; }
    }
}
