//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class Devices_2015_07_01
    {
    	[DataMember]
        public string PhoneNumber { get; set; }
    	[DataMember]
        public Nullable<int> DeviceType { get; set; }
    	[DataMember]
        public Nullable<int> Provider { get; set; }
    	[DataMember]
        public Nullable<int> MonthAdd { get; set; }
    	[DataMember]
        public Nullable<int> MonthOut { get; set; }
    	[DataMember]
        public string Account { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public string SubscriberName { get; set; }
    	[DataMember]
        public Nullable<bool> IsUnused { get; set; }
    	[DataMember]
        public Nullable<int> WorkStatus { get; set; }
    	[DataMember]
        public Nullable<int> ToBeOutOrderedDate { get; set; }
    	[DataMember]
        public string CTC_OutOrderNumber { get; set; }
    	[DataMember]
        public Nullable<int> CTC_Exemption { get; set; }
    	[DataMember]
        public Nullable<int> CTC_AccessoryStatus { get; set; }
    	[DataMember]
        public string CTC_ReasonForNotDisconnecting { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> CreatedDate { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    	[DataMember]
        public string ModifiedBy { get; set; }
    	[DataMember]
        public string SR { get; set; }
    	[DataMember]
        public string WO { get; set; }
    	[DataMember]
        public string LastName { get; set; }
    	[DataMember]
        public string FirstName { get; set; }
    	[DataMember]
        public string Email { get; set; }
    	[DataMember]
        public string WorkLocation { get; set; }
    	[DataMember]
        public string Province { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public Nullable<int> Country { get; set; }
    }
}
