//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(AccessoryStatu))]
    [KnownType(typeof(Department))]
    [KnownType(typeof(EAP_STATUS))]
    [KnownType(typeof(ExemptionType))]
    [KnownType(typeof(KeepChoice))]
    [KnownType(typeof(LineUsage))]
    [KnownType(typeof(Province))]
    [KnownType(typeof(ServiceProvider))]
    [KnownType(typeof(SoReason))]
    [KnownType(typeof(UsocType))]
    [KnownType(typeof(DeviceTypesFromBilling))]
    
    public partial class Devices_History
    {
    	[DataMember]
        public string PhoneNumber { get; set; }
    	[DataMember]
        public Nullable<int> LineCategory { get; set; }
    	[DataMember]
        public Nullable<int> Provider { get; set; }
    	[DataMember]
        public Nullable<int> MonthAdd { get; set; }
    	[DataMember]
        public Nullable<int> MonthOut { get; set; }
    	[DataMember]
        public string Account { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public string SubscriberName { get; set; }
    	[DataMember]
        public Nullable<bool> IsUnused { get; set; }
    	[DataMember]
        public Nullable<int> LineStatus { get; set; }
    	[DataMember]
        public string SoNumber { get; set; }
    	[DataMember]
        public Nullable<int> CTC_Exemption { get; set; }
    	[DataMember]
        public Nullable<int> CTC_AccessoryStatus { get; set; }
    	[DataMember]
        public string CTC_Comment { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> CreatedDate { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    	[DataMember]
        public string ModifiedBy { get; set; }
    	[DataMember]
        public string SoDueDate { get; set; }
    	[DataMember]
        public string EAP_Comments { get; set; }
    	[DataMember]
        public string StreetAddress { get; set; }
    	[DataMember]
        public string Province { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public Nullable<int> Country { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> TBOO_DATE { get; set; }
    	[DataMember]
        public string KeepJustification { get; set; }
    	[DataMember]
        public Nullable<int> KeepChoice { get; set; }
    	[DataMember]
        public Nullable<int> USOC { get; set; }
    	[DataMember]
        public string Email { get; set; }
    	[DataMember]
        public string ApproverEmail { get; set; }
    	[DataMember]
        public Nullable<int> LineUsage { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ExemptionDate { get; set; }
    	[DataMember]
        public string LastName { get; set; }
    	[DataMember]
        public string FirstName { get; set; }
    	[DataMember]
        public string EmployeeComments { get; set; }
    	[DataMember]
        public int Version { get; set; }
    	[DataMember]
        public Nullable<int> DepartmentFromBilling { get; set; }
    	[DataMember]
        public Nullable<int> SoReason { get; set; }
    	[DataMember]
        public string Building { get; set; }
    
    	[DataMember]
        public virtual AccessoryStatu AccessoryStatu { get; set; }
    	[DataMember]
        public virtual Department Department1 { get; set; }
    	[DataMember]
        public virtual Department Department2 { get; set; }
    	[DataMember]
        public virtual EAP_STATUS EAP_STATUS { get; set; }
    	[DataMember]
        public virtual ExemptionType ExemptionType { get; set; }
    	[DataMember]
        public virtual KeepChoice KeepChoice1 { get; set; }
    	[DataMember]
        public virtual LineUsage LineUsage1 { get; set; }
    	[DataMember]
        public virtual Province Province1 { get; set; }
    	[DataMember]
        public virtual ServiceProvider ServiceProvider { get; set; }
    	[DataMember]
        public virtual SoReason SoReason1 { get; set; }
    	[DataMember]
        public virtual UsocType UsocType { get; set; }
    	[DataMember]
        public virtual DeviceTypesFromBilling DeviceTypesFromBilling { get; set; }
    }
}
