//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DRDB : DbContext
    {
    	public DRDB()
            : this(false) { }
    
        public DRDB(bool proxyCreationEnabled)
            : base("name=DRDB")
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    	
        public DRDB(string connectionString)
          : this(connectionString, false) { }
    	  
        public DRDB(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    	
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessoryStatu> AccessoryStatus { get; set; }
        public virtual DbSet<ActionLog> ActionLogs { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_UsersInRoles> aspnet_UsersInRoles { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<BellCostFromWL> BellCostFromWLs { get; set; }
        public virtual DbSet<BellCostFromWL_2014_01> BellCostFromWL_2014_01 { get; set; }
        public virtual DbSet<BellCostFromWL_2014_04> BellCostFromWL_2014_04 { get; set; }
        public virtual DbSet<BellCostFromWL_2014_08> BellCostFromWL_2014_08 { get; set; }
        public virtual DbSet<BellCostFromWL_2014_09> BellCostFromWL_2014_09 { get; set; }
        public virtual DbSet<BellCostFromWL_2014_10> BellCostFromWL_2014_10 { get; set; }
        public virtual DbSet<BellCostFromWL_2014_11> BellCostFromWL_2014_11 { get; set; }
        public virtual DbSet<BellUsageFromWL> BellUsageFromWLs { get; set; }
        public virtual DbSet<BellUsageFromWL_2014_01> BellUsageFromWL_2014_01 { get; set; }
        public virtual DbSet<BellUsageFromWL_2014_04> BellUsageFromWL_2014_04 { get; set; }
        public virtual DbSet<BellUsageFromWL_2014_08> BellUsageFromWL_2014_08 { get; set; }
        public virtual DbSet<BellUsageFromWL_2014_09> BellUsageFromWL_2014_09 { get; set; }
        public virtual DbSet<BellUsageFromWL_2014_10> BellUsageFromWL_2014_10 { get; set; }
        public virtual DbSet<BellUsageFromWL_2014_11> BellUsageFromWL_2014_11 { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BuildingDetail> BuildingDetails { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<BulkDataEntry> BulkDataEntries { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CRA> CRAs { get; set; }
        public virtual DbSet<DepartmentAgency> DepartmentAgencies { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Devices_History> Devices_History { get; set; }
        public virtual DbSet<DeviceTypesFromBilling> DeviceTypesFromBillings { get; set; }
        public virtual DbSet<DeviceTypesFromSurvey> DeviceTypesFromSurveys { get; set; }
        public virtual DbSet<DialerStatu> DialerStatus { get; set; }
        public virtual DbSet<EAP_STATUS> EAP_STATUS { get; set; }
        public virtual DbSet<EAP_STATUS_V2> EAP_STATUS_V2 { get; set; }
        public virtual DbSet<ExemptionType> ExemptionTypes { get; set; }
        public virtual DbSet<HighUsageExemption> HighUsageExemptions { get; set; }
        public virtual DbSet<HighUsageExemptionType> HighUsageExemptionTypes { get; set; }
        public virtual DbSet<InterestType> InterestTypes { get; set; }
        public virtual DbSet<KeepChoice> KeepChoices { get; set; }
        public virtual DbSet<LandLineProvider> LandLineProviders { get; set; }
        public virtual DbSet<LandLineType> LandLineTypes { get; set; }
        public virtual DbSet<LineUsage> LineUsages { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<NAT_AB_BC> NAT_AB_BC { get; set; }
        public virtual DbSet<NAT_AB_BC_2014> NAT_AB_BC_2014 { get; set; }
        public virtual DbSet<NAT_AB_BC_2015> NAT_AB_BC_2015 { get; set; }
        public virtual DbSet<NAT_ALIANT> NAT_ALIANT { get; set; }
        public virtual DbSet<NAT_DMS> NAT_DMS { get; set; }
        public virtual DbSet<NAT_DMS_2014> NAT_DMS_2014 { get; set; }
        public virtual DbSet<NAT_DMS_2015> NAT_DMS_2015 { get; set; }
        public virtual DbSet<NAT_EASTLINK> NAT_EASTLINK { get; set; }
        public virtual DbSet<NAT_MTS> NAT_MTS { get; set; }
        public virtual DbSet<NAT_MTS_2014> NAT_MTS_2014 { get; set; }
        public virtual DbSet<NAT_NWTel> NAT_NWTel { get; set; }
        public virtual DbSet<NAT_Sasktel> NAT_Sasktel { get; set; }
        public virtual DbSet<NAT_Sasktel_2014> NAT_Sasktel_2014 { get; set; }
        public virtual DbSet<OLD_Quarters> OLD_Quarters { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<PrimaryUse> PrimaryUses { get; set; }
        public virtual DbSet<ProtectedType> ProtectedTypes { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<RegistrationsV2> RegistrationsV2 { get; set; }
        public virtual DbSet<RogersCostFromWL> RogersCostFromWLs { get; set; }
        public virtual DbSet<RogersCostFromWL_2014_01> RogersCostFromWL_2014_01 { get; set; }
        public virtual DbSet<RogersCostFromWL_2014_04> RogersCostFromWL_2014_04 { get; set; }
        public virtual DbSet<RogersCostFromWL_2014_08> RogersCostFromWL_2014_08 { get; set; }
        public virtual DbSet<RogersCostFromWL_2014_09> RogersCostFromWL_2014_09 { get; set; }
        public virtual DbSet<RogersCostFromWL_2014_10> RogersCostFromWL_2014_10 { get; set; }
        public virtual DbSet<RogersCostFromWL_2014_11> RogersCostFromWL_2014_11 { get; set; }
        public virtual DbSet<RogersUsageFromWL> RogersUsageFromWLs { get; set; }
        public virtual DbSet<RogersUsageFromWL_2014_01> RogersUsageFromWL_2014_01 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2014_04> RogersUsageFromWL_2014_04 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2014_08> RogersUsageFromWL_2014_08 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2014_09> RogersUsageFromWL_2014_09 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2014_10> RogersUsageFromWL_2014_10 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2014_11> RogersUsageFromWL_2014_11 { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
        public virtual DbSet<SoReason> SoReasons { get; set; }
        public virtual DbSet<TelusCostFromWL> TelusCostFromWLs { get; set; }
        public virtual DbSet<TelusUsageFromWL> TelusUsageFromWLs { get; set; }
        public virtual DbSet<TenantType> TenantTypes { get; set; }
        public virtual DbSet<UnusedWL_WP> UnusedWL_WP { get; set; }
        public virtual DbSet<USOC> USOCs { get; set; }
        public virtual DbSet<UsocType> UsocTypes { get; set; }
        public virtual DbSet<WirelessStatu> WirelessStatus { get; set; }
        public virtual DbSet<WL_2014_01> WL_2014_01 { get; set; }
        public virtual DbSet<WL_2014_04> WL_2014_04 { get; set; }
        public virtual DbSet<aspnet_Membership_backup> aspnet_Membership_backup { get; set; }
        public virtual DbSet<BellCostFromWL_2014_12> BellCostFromWL_2014_12 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_01> BellCostFromWL_2015_01 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_02> BellCostFromWL_2015_02 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_03> BellCostFromWL_2015_03 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_04> BellCostFromWL_2015_04 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_05> BellCostFromWL_2015_05 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_06> BellCostFromWL_2015_06 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_07> BellCostFromWL_2015_07 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_08> BellCostFromWL_2015_08 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_09> BellCostFromWL_2015_09 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_10> BellCostFromWL_2015_10 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_11> BellCostFromWL_2015_11 { get; set; }
        public virtual DbSet<BellCostFromWL_2015_12> BellCostFromWL_2015_12 { get; set; }
        public virtual DbSet<BellCostFromWL_2016_01> BellCostFromWL_2016_01 { get; set; }
        public virtual DbSet<BellFromEcare_2015_12> BellFromEcare_2015_12 { get; set; }
        public virtual DbSet<BellUsageFromWL_2014_12> BellUsageFromWL_2014_12 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_01> BellUsageFromWL_2015_01 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_02> BellUsageFromWL_2015_02 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_03> BellUsageFromWL_2015_03 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_04> BellUsageFromWL_2015_04 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_05> BellUsageFromWL_2015_05 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_06> BellUsageFromWL_2015_06 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_07> BellUsageFromWL_2015_07 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_08> BellUsageFromWL_2015_08 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_09> BellUsageFromWL_2015_09 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_10> BellUsageFromWL_2015_10 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_11> BellUsageFromWL_2015_11 { get; set; }
        public virtual DbSet<BellUsageFromWL_2015_12> BellUsageFromWL_2015_12 { get; set; }
        public virtual DbSet<BellUsageFromWL_2016_01> BellUsageFromWL_2016_01 { get; set; }
        public virtual DbSet<BuildingsWithNoPID> BuildingsWithNoPIDs { get; set; }
        public virtual DbSet<BuildingsWithNoSID> BuildingsWithNoSIDs { get; set; }
        public virtual DbSet<Devices_2015_07_01> Devices_2015_07_01 { get; set; }
        public virtual DbSet<Devices_2015_08_01> Devices_2015_08_01 { get; set; }
        public virtual DbSet<Devices_2015_09_01> Devices_2015_09_01 { get; set; }
        public virtual DbSet<Devices_2015_10_01> Devices_2015_10_01 { get; set; }
        public virtual DbSet<Devices_2015_11_01> Devices_2015_11_01 { get; set; }
        public virtual DbSet<Devices_2015_12_01> Devices_2015_12_01 { get; set; }
        public virtual DbSet<Devices_2016_01_01> Devices_2016_01_01 { get; set; }
        public virtual DbSet<Devices_2016_02_01> Devices_2016_02_01 { get; set; }
        public virtual DbSet<Devices_2016_02_05> Devices_2016_02_05 { get; set; }
        public virtual DbSet<Devices_2016_03_01> Devices_2016_03_01 { get; set; }
        public virtual DbSet<Devices_2016_04_01> Devices_2016_04_01 { get; set; }
        public virtual DbSet<Devices_2016_05_01> Devices_2016_05_01 { get; set; }
        public virtual DbSet<EAP_STATUS_2015_07_13> EAP_STATUS_2015_07_13 { get; set; }
        public virtual DbSet<NAT_ALIANT_2014> NAT_ALIANT_2014 { get; set; }
        public virtual DbSet<NAT_ALIANT_2015_10_OUT> NAT_ALIANT_2015_10_OUT { get; set; }
        public virtual DbSet<NAT_ALIANT_2015_10_OUT_B> NAT_ALIANT_2015_10_OUT_B { get; set; }
        public virtual DbSet<NAT_EASTLINK_2014> NAT_EASTLINK_2014 { get; set; }
        public virtual DbSet<NAT_EASTLINK_2015> NAT_EASTLINK_2015 { get; set; }
        public virtual DbSet<NAT_MTS_2015> NAT_MTS_2015 { get; set; }
        public virtual DbSet<NAT_NWTel_2014> NAT_NWTel_2014 { get; set; }
        public virtual DbSet<OBM> OBMs { get; set; }
        public virtual DbSet<OBM_HISTORY> OBM_HISTORY { get; set; }
        public virtual DbSet<RogersCostFromWL_2014_12> RogersCostFromWL_2014_12 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_01> RogersCostFromWL_2015_01 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_02> RogersCostFromWL_2015_02 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_03> RogersCostFromWL_2015_03 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_04> RogersCostFromWL_2015_04 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_05> RogersCostFromWL_2015_05 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_06> RogersCostFromWL_2015_06 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_07> RogersCostFromWL_2015_07 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_08> RogersCostFromWL_2015_08 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_09> RogersCostFromWL_2015_09 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_10> RogersCostFromWL_2015_10 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_11> RogersCostFromWL_2015_11 { get; set; }
        public virtual DbSet<RogersCostFromWL_2015_12> RogersCostFromWL_2015_12 { get; set; }
        public virtual DbSet<RogersCostFromWL_2016_01> RogersCostFromWL_2016_01 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2014_12> RogersUsageFromWL_2014_12 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_01> RogersUsageFromWL_2015_01 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_02> RogersUsageFromWL_2015_02 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_03> RogersUsageFromWL_2015_03 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_04> RogersUsageFromWL_2015_04 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_05> RogersUsageFromWL_2015_05 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_06> RogersUsageFromWL_2015_06 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_07> RogersUsageFromWL_2015_07 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_08> RogersUsageFromWL_2015_08 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_09> RogersUsageFromWL_2015_09 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_10> RogersUsageFromWL_2015_10 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_11> RogersUsageFromWL_2015_11 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2015_12> RogersUsageFromWL_2015_12 { get; set; }
        public virtual DbSet<RogersUsageFromWL_2016_01> RogersUsageFromWL_2016_01 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TelusCostFromWL_2014_08> TelusCostFromWL_2014_08 { get; set; }
        public virtual DbSet<TelusCostFromWL_2014_09> TelusCostFromWL_2014_09 { get; set; }
        public virtual DbSet<TelusCostFromWL_2014_10> TelusCostFromWL_2014_10 { get; set; }
        public virtual DbSet<TelusCostFromWL_2014_11> TelusCostFromWL_2014_11 { get; set; }
        public virtual DbSet<TelusCostFromWL_2014_12> TelusCostFromWL_2014_12 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_01> TelusCostFromWL_2015_01 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_02> TelusCostFromWL_2015_02 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_03> TelusCostFromWL_2015_03 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_04> TelusCostFromWL_2015_04 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_05> TelusCostFromWL_2015_05 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_06> TelusCostFromWL_2015_06 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_07> TelusCostFromWL_2015_07 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_08> TelusCostFromWL_2015_08 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_09> TelusCostFromWL_2015_09 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_10> TelusCostFromWL_2015_10 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_11> TelusCostFromWL_2015_11 { get; set; }
        public virtual DbSet<TelusCostFromWL_2015_12> TelusCostFromWL_2015_12 { get; set; }
        public virtual DbSet<TelusCostFromWL_2016_01> TelusCostFromWL_2016_01 { get; set; }
        public virtual DbSet<TelusEBOD_2014_08> TelusEBOD_2014_08 { get; set; }
        public virtual DbSet<TelusEBOD_2014_09> TelusEBOD_2014_09 { get; set; }
        public virtual DbSet<TelusEBOD_2014_10> TelusEBOD_2014_10 { get; set; }
        public virtual DbSet<TelusEBOD_2014_11> TelusEBOD_2014_11 { get; set; }
        public virtual DbSet<TelusEBOD_2014_12> TelusEBOD_2014_12 { get; set; }
        public virtual DbSet<TelusEBOD_2015_01> TelusEBOD_2015_01 { get; set; }
        public virtual DbSet<TelusEBOD_2015_02> TelusEBOD_2015_02 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2014_08> TelusUsageFromWL_2014_08 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2014_09> TelusUsageFromWL_2014_09 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2014_10> TelusUsageFromWL_2014_10 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2014_11> TelusUsageFromWL_2014_11 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2014_12> TelusUsageFromWL_2014_12 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_01> TelusUsageFromWL_2015_01 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_02> TelusUsageFromWL_2015_02 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_03> TelusUsageFromWL_2015_03 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_04> TelusUsageFromWL_2015_04 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_05> TelusUsageFromWL_2015_05 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_06> TelusUsageFromWL_2015_06 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_07> TelusUsageFromWL_2015_07 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_08> TelusUsageFromWL_2015_08 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_09> TelusUsageFromWL_2015_09 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_10> TelusUsageFromWL_2015_10 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_11> TelusUsageFromWL_2015_11 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2015_12> TelusUsageFromWL_2015_12 { get; set; }
        public virtual DbSet<TelusUsageFromWL_2016_01> TelusUsageFromWL_2016_01 { get; set; }
        public virtual DbSet<UnusedWL> UnusedWLs { get; set; }
        public virtual DbSet<UnusedWL_2014_04> UnusedWL_2014_04 { get; set; }
        public virtual DbSet<UnusedWL_2014_11> UnusedWL_2014_11 { get; set; }
        public virtual DbSet<UnusedWL_2015_11> UnusedWL_2015_11 { get; set; }
        public virtual DbSet<vw_aspnet_Applications> vw_aspnet_Applications { get; set; }
        public virtual DbSet<vw_aspnet_MembershipUsers> vw_aspnet_MembershipUsers { get; set; }
        public virtual DbSet<vw_aspnet_Profiles> vw_aspnet_Profiles { get; set; }
        public virtual DbSet<vw_aspnet_Roles> vw_aspnet_Roles { get; set; }
        public virtual DbSet<vw_aspnet_Users> vw_aspnet_Users { get; set; }
        public virtual DbSet<vw_aspnet_UsersInRoles> vw_aspnet_UsersInRoles { get; set; }
        public virtual DbSet<vw_aspnet_WebPartState_Paths> vw_aspnet_WebPartState_Paths { get; set; }
        public virtual DbSet<vw_aspnet_WebPartState_Shared> vw_aspnet_WebPartState_Shared { get; set; }
        public virtual DbSet<vw_aspnet_WebPartState_User> vw_aspnet_WebPartState_User { get; set; }
        public virtual DbSet<Wireless> Wirelesses { get; set; }
        public virtual DbSet<WL_2014_08> WL_2014_08 { get; set; }
        public virtual DbSet<WL_2014_09> WL_2014_09 { get; set; }
        public virtual DbSet<WL_2014_10> WL_2014_10 { get; set; }
        public virtual DbSet<WL_2014_11> WL_2014_11 { get; set; }
        public virtual DbSet<WL_2014_12> WL_2014_12 { get; set; }
        public virtual DbSet<WL_2015_01> WL_2015_01 { get; set; }
        public virtual DbSet<WL_2015_02> WL_2015_02 { get; set; }
        public virtual DbSet<WL_2015_03> WL_2015_03 { get; set; }
        public virtual DbSet<WL_2015_04> WL_2015_04 { get; set; }
        public virtual DbSet<WL_2015_05> WL_2015_05 { get; set; }
        public virtual DbSet<WL_2015_06> WL_2015_06 { get; set; }
        public virtual DbSet<WL_2015_07> WL_2015_07 { get; set; }
        public virtual DbSet<WL_2015_08> WL_2015_08 { get; set; }
        public virtual DbSet<WL_2015_09> WL_2015_09 { get; set; }
        public virtual DbSet<WL_2015_10> WL_2015_10 { get; set; }
        public virtual DbSet<WL_2015_11> WL_2015_11 { get; set; }
        public virtual DbSet<WL_2015_12> WL_2015_12 { get; set; }
        public virtual DbSet<WL_2016_01> WL_2016_01 { get; set; }
        public virtual DbSet<HighUsageFast> HighUsageFasts { get; set; }
    }
}
