//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class HighUsageFast
    {
    	[DataMember]
        public string BilledName { get; set; }
    	[DataMember]
        public string PhoneNumber { get; set; }
    	[DataMember]
        public string DeviceType { get; set; }
    	[DataMember]
        public string MonthlyCost2 { get; set; }
    	[DataMember]
        public Nullable<double> MonthlyCost { get; set; }
    	[DataMember]
        public Nullable<int> TotalNumberOfAirtimeMinutes { get; set; }
    	[DataMember]
        public string Usage { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public string Department_eng { get; set; }
    	[DataMember]
        public string Provider { get; set; }
    	[DataMember]
        public int EDMXID { get; set; }
    }
}
