//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(DeviceTypesFromBilling))]
    [KnownType(typeof(HighUsageExemptionType))]
    
    public partial class HighUsageExemption
    {
    	[DataMember]
        public string CellularNumber { get; set; }
    	[DataMember]
        public int Exemption { get; set; }
    	[DataMember]
        public string Justification { get; set; }
    	[DataMember]
        public string NameFromBilling { get; set; }
    	[DataMember]
        public Nullable<int> DeviceTypeFromBilling { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Created { get; set; }
    	[DataMember]
        public string CreatedBy { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Modified { get; set; }
    	[DataMember]
        public string ModifiedBy { get; set; }
    
    	[DataMember]
        public virtual DeviceTypesFromBilling DeviceTypesFromBilling { get; set; }
    	[DataMember]
        public virtual HighUsageExemptionType HighUsageExemptionType { get; set; }
    }
}
