//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class NAT_Sasktel_2014
    {
    	[DataMember]
        public string Number { get; set; }
    	[DataMember]
        public Nullable<int> Registration { get; set; }
    	[DataMember]
        public string Account { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public Nullable<int> DepartmentAgency { get; set; }
    	[DataMember]
        public string CustomerNumber { get; set; }
    	[DataMember]
        public string Customer { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Address { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string Province { get; set; }
    	[DataMember]
        public string Dist { get; set; }
    	[DataMember]
        public string USOC1 { get; set; }
    	[DataMember]
        public string UsocDesc1 { get; set; }
    	[DataMember]
        public string Qte1 { get; set; }
    	[DataMember]
        public string USOC2 { get; set; }
    	[DataMember]
        public string UsocDesc2 { get; set; }
    	[DataMember]
        public string Qte2 { get; set; }
    }
}
