//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class NAT_ALIANT_2015_10_OUT
    {
    	[DataMember]
        public string Number { get; set; }
    	[DataMember]
        public Nullable<int> Registration { get; set; }
    	[DataMember]
        public string Account { get; set; }
    	[DataMember]
        public string Date { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public string Department_eng { get; set; }
    	[DataMember]
        public string DeptIdFromAliant { get; set; }
    	[DataMember]
        public Nullable<int> DepartmentAgency { get; set; }
    }
}
