//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class NAT_EASTLINK_2014
    {
    	[DataMember]
        public string Number { get; set; }
    	[DataMember]
        public Nullable<int> Registration { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public Nullable<int> DepartmentAgency { get; set; }
    	[DataMember]
        public string Dept { get; set; }
    	[DataMember]
        public string Customer { get; set; }
    	[DataMember]
        public string Address { get; set; }
    	[DataMember]
        public string Province { get; set; }
    	[DataMember]
        public Nullable<double> NCOS { get; set; }
    	[DataMember]
        public string Features1 { get; set; }
    	[DataMember]
        public string Features2 { get; set; }
    	[DataMember]
        public string Features3 { get; set; }
    	[DataMember]
        public string LineType { get; set; }
    }
}
