//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class NAT_AB_BC
    {
    	[DataMember]
        public string Number { get; set; }
    	[DataMember]
        public Nullable<int> Registration { get; set; }
    	[DataMember]
        public string BTN { get; set; }
    	[DataMember]
        public string WTN { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public Nullable<int> DepartmentAgency { get; set; }
    	[DataMember]
        public string CustomerName { get; set; }
    	[DataMember]
        public string Address { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public string Province { get; set; }
    	[DataMember]
        public string RCID { get; set; }
    	[DataMember]
        public string StartDate { get; set; }
    	[DataMember]
        public string EndDate { get; set; }
    	[DataMember]
        public string JAN2014 { get; set; }
    	[DataMember]
        public string FEB2014 { get; set; }
    	[DataMember]
        public string MAR2014 { get; set; }
    }
}
