//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class NAT_MTS_2015
    {
    	[DataMember]
        public string Number { get; set; }
    	[DataMember]
        public Nullable<int> Registration { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public Nullable<int> DepartmentAgency { get; set; }
    	[DataMember]
        public string CustomerID { get; set; }
    	[DataMember]
        public string CustomerName { get; set; }
    	[DataMember]
        public string BillingAggregatorID { get; set; }
    	[DataMember]
        public string BillingAggregatorCIN { get; set; }
    	[DataMember]
        public string BillingAggregatorName { get; set; }
    	[DataMember]
        public string BillingAccountID { get; set; }
    	[DataMember]
        public string BillingAccountName { get; set; }
    	[DataMember]
        public string UnitID { get; set; }
    	[DataMember]
        public string UnitServiceType { get; set; }
    	[DataMember]
        public string LocationID { get; set; }
    	[DataMember]
        public string StreetNumber { get; set; }
    	[DataMember]
        public string StreetName { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string Province { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public string AnalogDigital { get; set; }
    }
}
