//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class OBM_HISTORY
    {
    	[DataMember]
        public string NumberBilled { get; set; }
    	[DataMember]
        public string Information { get; set; }
    	[DataMember]
        public string Level3Node { get; set; }
    	[DataMember]
        public string Level4Node { get; set; }
    	[DataMember]
        public string AccountNumber { get; set; }
    	[DataMember]
        public Nullable<int> RegistrationsID { get; set; }
    	[DataMember]
        public Nullable<int> DepartmentFromOBM { get; set; }
    	[DataMember]
        public string Month { get; set; }
    }
}
