//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Department))]
    
    public partial class Portfolio
    {
        public Portfolio()
        {
            this.Departments = new HashSet<Department>();
        }
    
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string Portfolio_eng { get; set; }
    	[DataMember]
        public string Portfolio_fra { get; set; }
    
    	[DataMember]
        public virtual ICollection<Department> Departments { get; set; }
    }
}
