//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Registration))]
    
    public partial class ProtectedType
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public Nullable<bool> Name { get; set; }
    	[DataMember]
        public Nullable<bool> SocialNumber { get; set; }
    	[DataMember]
        public Nullable<bool> TaxPayerSalary { get; set; }
    	[DataMember]
        public Nullable<bool> PRI { get; set; }
    	[DataMember]
        public Nullable<bool> EmployeeSalary { get; set; }
    	[DataMember]
        public Nullable<bool> LetterOfOffer { get; set; }
    	[DataMember]
        public Nullable<bool> LearningPlan { get; set; }
    	[DataMember]
        public Nullable<bool> PerformanceEval { get; set; }
    	[DataMember]
        public Nullable<bool> Audit { get; set; }
    	[DataMember]
        public Nullable<bool> Design { get; set; }
    	[DataMember]
        public Nullable<bool> SecurityEval { get; set; }
    	[DataMember]
        public Nullable<bool> OtherProtectedType { get; set; }
    	[DataMember]
        public string OtherProtectedTypeDesc { get; set; }
    
    	[DataMember]
        public virtual Registration Registration { get; set; }
    }
}
