//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(City))]
    [KnownType(typeof(Device))]
    [KnownType(typeof(Devices_History))]
    [KnownType(typeof(Location))]
    
    public partial class Province
    {
        public Province()
        {
            this.Cities = new HashSet<City>();
            this.Devices = new HashSet<Device>();
            this.Devices_History = new HashSet<Devices_History>();
            this.Locations = new HashSet<Location>();
        }
    
    	[DataMember]
        public string PROV_CD { get; set; }
    	[DataMember]
        public string FK_COUNTRY_CD { get; set; }
    	[DataMember]
        public string PROV_ENG_NM { get; set; }
    	[DataMember]
        public string PROV_FR_NM { get; set; }
    
    	[DataMember]
        public virtual ICollection<City> Cities { get; set; }
    	[DataMember]
        public virtual ICollection<Device> Devices { get; set; }
    	[DataMember]
        public virtual ICollection<Devices_History> Devices_History { get; set; }
    	[DataMember]
        public virtual ICollection<Location> Locations { get; set; }
    }
}
