//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Building))]
    [KnownType(typeof(Country))]
    [KnownType(typeof(Department))]
    
    public partial class RegistrationsV2
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string LastName { get; set; }
    	[DataMember]
        public string FirstName { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public string LandLine { get; set; }
    	[DataMember]
        public string Extension { get; set; }
    	[DataMember]
        public string Fax { get; set; }
    	[DataMember]
        public string VoipLine { get; set; }
    	[DataMember]
        public string CellularNumber1 { get; set; }
    	[DataMember]
        public string CellularNumber2 { get; set; }
    	[DataMember]
        public string CellularNumber3 { get; set; }
    	[DataMember]
        public string Comments { get; set; }
    	[DataMember]
        public Nullable<long> Building { get; set; }
    	[DataMember]
        public Nullable<double> BuildingPrecision { get; set; }
    	[DataMember]
        public string WorkLocation { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public string Province { get; set; }
    	[DataMember]
        public Nullable<int> Country { get; set; }
    	[DataMember]
        public string SupervisorName { get; set; }
    	[DataMember]
        public string SupervisorPhone { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> CreatedDate { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    	[DataMember]
        public string ModifiedBy { get; set; }
    
    	[DataMember]
        public virtual Building Building1 { get; set; }
    	[DataMember]
        public virtual Country Country1 { get; set; }
    	[DataMember]
        public virtual Department Department1 { get; set; }
    }
}
