//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Device))]
    [KnownType(typeof(Devices_History))]
    [KnownType(typeof(Registration))]
    [KnownType(typeof(UnusedWL))]
    [KnownType(typeof(UnusedWL_WP))]
    [KnownType(typeof(Wireless))]
    
    public partial class ServiceProvider
    {
        public ServiceProvider()
        {
            this.Devices = new HashSet<Device>();
            this.Devices_History = new HashSet<Devices_History>();
            this.Registrations = new HashSet<Registration>();
            this.Registrations1 = new HashSet<Registration>();
            this.Registrations2 = new HashSet<Registration>();
            this.Registrations3 = new HashSet<Registration>();
            this.UnusedWLs = new HashSet<UnusedWL>();
            this.UnusedWL_WP = new HashSet<UnusedWL_WP>();
            this.Wirelesses = new HashSet<Wireless>();
        }
    
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string ServiceProvider_eng { get; set; }
    	[DataMember]
        public string ServiceProvider_fra { get; set; }
    
    	[DataMember]
        public virtual ICollection<Device> Devices { get; set; }
    	[DataMember]
        public virtual ICollection<Devices_History> Devices_History { get; set; }
    	[DataMember]
        public virtual ICollection<Registration> Registrations { get; set; }
    	[DataMember]
        public virtual ICollection<Registration> Registrations1 { get; set; }
    	[DataMember]
        public virtual ICollection<Registration> Registrations2 { get; set; }
    	[DataMember]
        public virtual ICollection<Registration> Registrations3 { get; set; }
    	[DataMember]
        public virtual ICollection<UnusedWL> UnusedWLs { get; set; }
    	[DataMember]
        public virtual ICollection<UnusedWL_WP> UnusedWL_WP { get; set; }
    	[DataMember]
        public virtual ICollection<Wireless> Wirelesses { get; set; }
    }
}
