//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Department))]
    [KnownType(typeof(DeviceTypesFromBilling))]
    [KnownType(typeof(ServiceProvider))]
    [KnownType(typeof(WirelessStatu))]
    
    public partial class UnusedWL_WP
    {
    	[DataMember]
        public string SubscriberPhoneNo { get; set; }
    	[DataMember]
        public string SubscriberName { get; set; }
    	[DataMember]
        public Nullable<int> TypeOfDevice { get; set; }
    	[DataMember]
        public Nullable<int> Department { get; set; }
    	[DataMember]
        public string LastName { get; set; }
    	[DataMember]
        public string FirstName { get; set; }
    	[DataMember]
        public string Email { get; set; }
    	[DataMember]
        public Nullable<bool> IsKeepRequested { get; set; }
    	[DataMember]
        public string ReasonToKeep { get; set; }
    	[DataMember]
        public Nullable<bool> IsDeviceToBeReturned { get; set; }
    	[DataMember]
        public Nullable<int> ServiceProvider { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ActivationDate { get; set; }
    	[DataMember]
        public string StatusOfDevice { get; set; }
    	[DataMember]
        public Nullable<int> Status { get; set; }
    
    	[DataMember]
        public virtual Department Department1 { get; set; }
    	[DataMember]
        public virtual DeviceTypesFromBilling DeviceTypesFromBilling { get; set; }
    	[DataMember]
        public virtual ServiceProvider ServiceProvider1 { get; set; }
    	[DataMember]
        public virtual WirelessStatu WirelessStatu { get; set; }
    }
}
