//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(UsocType))]
    
    public partial class USOC
    {
    	[DataMember]
        public string USOC1 { get; set; }
    	[DataMember]
        public string ShortDesc { get; set; }
    	[DataMember]
        public Nullable<int> Type { get; set; }
    
    	[DataMember]
        public virtual UsocType UsocType { get; set; }
    }
}
