//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReporter
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(UnusedWL_WP))]
    
    public partial class WirelessStatu
    {
        public WirelessStatu()
        {
            this.UnusedWL_WP = new HashSet<UnusedWL_WP>();
        }
    
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string Status_eng { get; set; }
    
    	[DataMember]
        public virtual ICollection<UnusedWL_WP> UnusedWL_WP { get; set; }
    }
}
